CREATE TABLE "Product" (
  "id" TEXT NOT NULL, "source" TEXT NOT NULL DEFAULT 'dummyjson', "remoteId" INTEGER NOT NULL,
  "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT NOT NULL, "category" TEXT NOT NULL,
  "pricePaise" INTEGER NOT NULL, "discountPercentage" DOUBLE PRECISION, "rating" DOUBLE PRECISION NOT NULL,
  "stock" INTEGER NOT NULL, "brand" TEXT, "sku" TEXT NOT NULL, "imageUrl" TEXT NOT NULL,
  "imagesJson" TEXT NOT NULL, "tagsJson" TEXT NOT NULL, "attributesJson" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "CartSession" ("id" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CartSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CartItem" ("id" TEXT NOT NULL, "cartId" TEXT NOT NULL, "productId" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CartItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AgentDelegation" ("id" TEXT NOT NULL, "agentId" TEXT NOT NULL, "name" TEXT NOT NULL, "totalLimitPaise" INTEGER NOT NULL, "perTransactionLimitPaise" INTEGER NOT NULL, "transactionCountLimit" INTEGER NOT NULL, "frequencyCount" INTEGER NOT NULL, "frequencyUnit" TEXT NOT NULL, "allowedCategoriesJson" TEXT NOT NULL, "allowedMerchantsJson" TEXT NOT NULL, "currency" TEXT NOT NULL DEFAULT 'INR', "sentinelSecretEncrypted" TEXT, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AgentDelegation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RequestNonce" ("id" TEXT NOT NULL, "requestId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RequestNonce_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SentinelAuthorization" ("id" TEXT NOT NULL, "authorizationId" TEXT NOT NULL, "requestId" TEXT NOT NULL, "agentDelegationId" TEXT, "agentId" TEXT NOT NULL, "proposalFingerprint" TEXT NOT NULL, "amountPaise" INTEGER NOT NULL, "verdict" TEXT NOT NULL, "reasonCode" TEXT NOT NULL, "reasonMessage" TEXT NOT NULL, "proposalJson" TEXT NOT NULL, "checksJson" TEXT NOT NULL, "scenario" TEXT NOT NULL DEFAULT 'normal', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SentinelAuthorization_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AiAction" ("id" TEXT NOT NULL, "actionType" TEXT NOT NULL, "inputSummary" TEXT NOT NULL, "outputSummary" TEXT NOT NULL, "metadataJson" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AiAction_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Product_remoteId_key" ON "Product"("remoteId"); CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug"); CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku"); CREATE INDEX "Product_category_idx" ON "Product"("category"); CREATE INDEX "Product_pricePaise_idx" ON "Product"("pricePaise"); CREATE INDEX "Product_stock_idx" ON "Product"("stock");
CREATE INDEX "CartItem_cartId_idx" ON "CartItem"("cartId"); CREATE UNIQUE INDEX "CartItem_cartId_productId_key" ON "CartItem"("cartId", "productId"); CREATE UNIQUE INDEX "AgentDelegation_agentId_key" ON "AgentDelegation"("agentId"); CREATE INDEX "AgentDelegation_expiresAt_idx" ON "AgentDelegation"("expiresAt"); CREATE UNIQUE INDEX "RequestNonce_requestId_key" ON "RequestNonce"("requestId"); CREATE UNIQUE INDEX "SentinelAuthorization_authorizationId_key" ON "SentinelAuthorization"("authorizationId"); CREATE INDEX "SentinelAuthorization_agentId_createdAt_idx" ON "SentinelAuthorization"("agentId", "createdAt"); CREATE INDEX "SentinelAuthorization_requestId_idx" ON "SentinelAuthorization"("requestId"); CREATE INDEX "SentinelAuthorization_verdict_idx" ON "SentinelAuthorization"("verdict"); CREATE INDEX "AiAction_createdAt_idx" ON "AiAction"("createdAt"); CREATE INDEX "AiAction_actionType_idx" ON "AiAction"("actionType");
ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "CartSession"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "SentinelAuthorization" ADD CONSTRAINT "SentinelAuthorization_agentDelegationId_fkey" FOREIGN KEY ("agentDelegationId") REFERENCES "AgentDelegation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
